version: '3'
services:

  postgre_db:
    image: "postgres"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hyy19960529
    networks: 
      - twinet            

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - twinet 

  amqp_service:
    image: "rabbitmq:3.7.4"
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks: 
      - twinet 

  api_gateway:
    image: twitter_gateway_service
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet 

  auth_service:
    image: twitter_auth_service
    deploy:
      replicas: 2
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet 

  email_service:
    image: twitter_email_service
    deploy:
      replicas: 1
      restart_policy: 
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet 

  profile_service:
    image: twitter_profile_service
    deploy:
      replicas: 1
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet 

  tweet_service:
    image: twitter_tweet_service
    deploy:
      replicas: 1
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - twinet

networks: 
  twinet:
