apiVersion: v1
kind: Service
metadata:
  labels:
    twitter: amqp-service
  name: amqp-service
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    twitter: amqp-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    twitter: amqp-service
  name: amqp-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        twitter: amqp-service
    spec:
      containers:
      - image: rabbitmq
        name: amqp-service
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m