apiVersion: v1
kind: Service
metadata:
  labels:
    twitter: amqp-service
  name: amqp-service
spec:
  ports:
  - name: service
    port: 5672
    targetPort: 5672
  - name: interface
    port: 15672
    targetPort: 15672
  selector:
    twitter: amqp-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    twitter: amqp-service
  name: amqp-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        twitter: amqp-service
    spec:
      containers:
      - image: rabbitmq:3.7.4-management
        name: amqp-service
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 100m