apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    twitter: api-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    twitter: api-gateway
  externalIPs:
    - 10.0.1.15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    twitter: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      twitter: api-gateway
  template:
    metadata:
      labels: 
        twitter: api-gateway
    spec:
      containers:
      - image: richackard/twitter_gateway_service
        name: api-gateway
        ports:
          - containerPort: 80
      restartPolicy: Always