apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    twitter: api-gateway
  name: api-gateway
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        twitter: api-gateway
    spec:
      containers:
      - image: richackard/twitter_gateway_service
        name: api-gateway
        ports:
          - containerPort: 80
      restartPolicy: Always